# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)


class Point(google___protobuf___message___Message):
    x = ... # type: float
    y = ... # type: float

    def __init__(self,
        x : typing___Optional[float] = None,
        y : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Point: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Interval(google___protobuf___message___Message):
    a = ... # type: float
    b = ... # type: float

    def __init__(self,
        a : typing___Optional[float] = None,
        b : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Interval: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class BBox(google___protobuf___message___Message):

    @property
    def ix(self) -> Interval: ...

    @property
    def iy(self) -> Interval: ...

    def __init__(self,
        ix : typing___Optional[Interval] = None,
        iy : typing___Optional[Interval] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> BBox: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
