# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Point(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    x: builtin___float = ...
    y: builtin___float = ...

    def __init__(self,
        *,
        x : typing___Optional[builtin___float] = None,
        y : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y"]) -> None: ...
type___Point = Point

class Interval(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    a: builtin___float = ...
    b: builtin___float = ...

    def __init__(self,
        *,
        a : typing___Optional[builtin___float] = None,
        b : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b"]) -> None: ...
type___Interval = Interval

class BBox(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def ix(self) -> type___Interval: ...

    @property
    def iy(self) -> type___Interval: ...

    def __init__(self,
        *,
        ix : typing___Optional[type___Interval] = None,
        iy : typing___Optional[type___Interval] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ix",b"ix",u"iy",b"iy"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ix",b"ix",u"iy",b"iy"]) -> None: ...
type___BBox = BBox
