@startuml

title Foundation System

participant "Python Wrapper" as py
participant "Python Proto" as pyproto
participant "Serialized Proto" as proto
participant "JSON" as json
participant "TypeScript "

py <-> pyproto
pyproto <-> proto
pyproto <-> json

@enduml