# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from foundation.protos.geometry_pb2 import (
    BBox as foundation___protos___geometry_pb2___BBox,
)

from foundation.protos.ocr.types_pb2 import (
    InputWord as foundation___protos___ocr___types_pb2___InputWord,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)


class Entity(google___protobuf___message___Message):

    @property
    def word(self) -> Word: ...

    @property
    def line(self) -> Line: ...

    @property
    def paragraph(self) -> Paragraph: ...

    @property
    def table_cell(self) -> TableCell: ...

    @property
    def table_row(self) -> TableRow: ...

    @property
    def table(self) -> Table: ...

    @property
    def number(self) -> Number: ...

    @property
    def integer(self) -> Integer: ...

    @property
    def date(self) -> Date: ...

    @property
    def time(self) -> Time: ...

    @property
    def currency(self) -> Currency: ...

    @property
    def name(self) -> PersonName: ...

    @property
    def address(self) -> Address: ...

    @property
    def cluster(self) -> Cluster: ...

    @property
    def custom(self) -> GenericEntity: ...

    def __init__(self,
        word : typing___Optional[Word] = None,
        line : typing___Optional[Line] = None,
        paragraph : typing___Optional[Paragraph] = None,
        table_cell : typing___Optional[TableCell] = None,
        table_row : typing___Optional[TableRow] = None,
        table : typing___Optional[Table] = None,
        number : typing___Optional[Number] = None,
        integer : typing___Optional[Integer] = None,
        date : typing___Optional[Date] = None,
        time : typing___Optional[Time] = None,
        currency : typing___Optional[Currency] = None,
        name : typing___Optional[PersonName] = None,
        address : typing___Optional[Address] = None,
        cluster : typing___Optional[Cluster] = None,
        custom : typing___Optional[GenericEntity] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Entity: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GenericEntity(google___protobuf___message___Message):
    type = ... # type: typing___Text
    data = ... # type: bytes

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        type : typing___Text,
        data : bytes,
        bbox : foundation___protos___geometry_pb2___BBox,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GenericEntity: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Word(google___protobuf___message___Message):
    text = ... # type: typing___Text

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    @property
    def origin(self) -> foundation___protos___ocr___types_pb2___InputWord: ...

    def __init__(self,
        text : typing___Text,
        bbox : foundation___protos___geometry_pb2___BBox,
        origin : typing___Optional[foundation___protos___ocr___types_pb2___InputWord] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Word: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Line(google___protobuf___message___Message):

    @property
    def words(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        words : typing___Optional[typing___Iterable[Word]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Line: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Paragraph(google___protobuf___message___Message):

    @property
    def lines(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Line]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        lines : typing___Optional[typing___Iterable[Line]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Paragraph: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class TableCell(google___protobuf___message___Message):

    @property
    def content(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Entity]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        content : typing___Optional[typing___Iterable[Entity]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TableCell: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class TableRow(google___protobuf___message___Message):

    @property
    def cells(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[TableCell]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        cells : typing___Optional[typing___Iterable[TableCell]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TableRow: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Table(google___protobuf___message___Message):

    @property
    def rows(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[TableRow]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        rows : typing___Optional[typing___Iterable[TableRow]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Table: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Number(google___protobuf___message___Message):
    value = ... # type: float

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Word]] = None,
        value : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Number: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Integer(google___protobuf___message___Message):
    value = ... # type: int

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Word]] = None,
        value : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Integer: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Date(google___protobuf___message___Message):
    value = ... # type: typing___Text

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Word]] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Date: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Time(google___protobuf___message___Message):
    value = ... # type: int

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Word]] = None,
        value : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Time: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Currency(google___protobuf___message___Message):
    class FixedDecimal(google___protobuf___message___Message):
        integer_part = ... # type: int
        fractional_part = ... # type: int

        def __init__(self,
            integer_part : int,
            fractional_part : int,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> Currency.FixedDecimal: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

    units = ... # type: typing___Text

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Word]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    @property
    def value(self) -> Currency.FixedDecimal: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Word]] = None,
        value : typing___Optional[Currency.FixedDecimal] = None,
        units : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Currency: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class PersonName(google___protobuf___message___Message):
    value = ... # type: typing___Text

    @property
    def name_parts(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Line]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        name_parts : typing___Optional[typing___Iterable[Line]] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PersonName: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Address(google___protobuf___message___Message):
    value = ... # type: typing___Text

    @property
    def lines(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Line]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        lines : typing___Optional[typing___Iterable[Line]] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Address: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Cluster(google___protobuf___message___Message):
    label = ... # type: typing___Text

    @property
    def span(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Line]: ...

    @property
    def bbox(self) -> foundation___protos___geometry_pb2___BBox: ...

    def __init__(self,
        bbox : foundation___protos___geometry_pb2___BBox,
        span : typing___Optional[typing___Iterable[Line]] = None,
        label : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Cluster: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
