# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from geometry_pb2 import (
    BBox as geometry_pb2___BBox,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)


class Word(google___protobuf___message___Message):
    word_id = ... # type: typing___Text
    text = ... # type: typing___Text

    @property
    def bbox(self) -> geometry_pb2___BBox: ...

    def __init__(self,
        word_id : typing___Optional[typing___Text] = None,
        text : typing___Optional[typing___Text] = None,
        bbox : typing___Optional[geometry_pb2___BBox] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Word: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
