# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from foundation.protos.geometry_pb2 import (
    BBox as foundation___protos___geometry_pb2___BBox,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)


class InputWord(google___protobuf___message___Message):
    text = ... # type: typing___Text
    line_height = ... # type: float
    word_width = ... # type: float
    char_width = ... # type: float
    rotation_angle = ... # type: float

    @property
    def bounding_box(self) -> foundation___protos___geometry_pb2___BBox: ...

    @property
    def confidence(self) -> WordConfidence: ...

    def __init__(self,
        bounding_box : foundation___protos___geometry_pb2___BBox,
        text : typing___Optional[typing___Text] = None,
        confidence : typing___Optional[WordConfidence] = None,
        line_height : typing___Optional[float] = None,
        word_width : typing___Optional[float] = None,
        char_width : typing___Optional[float] = None,
        rotation_angle : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> InputWord: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class WordConfidence(google___protobuf___message___Message):
    word_confidence = ... # type: float
    low_confidence = ... # type: bool

    @property
    def char_confidences(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[CharConfidence]: ...

    def __init__(self,
        word_confidence : typing___Optional[float] = None,
        low_confidence : typing___Optional[bool] = None,
        char_confidences : typing___Optional[typing___Iterable[CharConfidence]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> WordConfidence: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class CharConfidence(google___protobuf___message___Message):
    percentage = ... # type: float
    unsure = ... # type: bool

    def __init__(self,
        percentage : float,
        unsure : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> CharConfidence: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
