# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from foundation.protos.geometry_pb2 import (
    BBox as foundation___protos___geometry_pb2___BBox,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class InputWord(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    text: typing___Text = ...
    line_height: builtin___float = ...
    word_width: builtin___float = ...
    char_width: builtin___float = ...
    rotation_angle: builtin___float = ...

    @property
    def bounding_box(self) -> foundation___protos___geometry_pb2___BBox: ...

    @property
    def confidence(self) -> type___WordConfidence: ...

    def __init__(self,
        *,
        bounding_box : typing___Optional[foundation___protos___geometry_pb2___BBox] = None,
        text : typing___Optional[typing___Text] = None,
        confidence : typing___Optional[type___WordConfidence] = None,
        line_height : typing___Optional[builtin___float] = None,
        word_width : typing___Optional[builtin___float] = None,
        char_width : typing___Optional[builtin___float] = None,
        rotation_angle : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bounding_box",b"bounding_box",u"char_width",b"char_width",u"confidence",b"confidence",u"line_height",b"line_height",u"rotation_angle",b"rotation_angle",u"text",b"text",u"word_width",b"word_width"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bounding_box",b"bounding_box",u"char_width",b"char_width",u"confidence",b"confidence",u"line_height",b"line_height",u"rotation_angle",b"rotation_angle",u"text",b"text",u"word_width",b"word_width"]) -> None: ...
type___InputWord = InputWord

class WordConfidence(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    word_confidence: builtin___float = ...
    low_confidence: builtin___bool = ...

    @property
    def char_confidences(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CharConfidence]: ...

    def __init__(self,
        *,
        word_confidence : typing___Optional[builtin___float] = None,
        low_confidence : typing___Optional[builtin___bool] = None,
        char_confidences : typing___Optional[typing___Iterable[type___CharConfidence]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"low_confidence",b"low_confidence",u"word_confidence",b"word_confidence"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"char_confidences",b"char_confidences",u"low_confidence",b"low_confidence",u"word_confidence",b"word_confidence"]) -> None: ...
type___WordConfidence = WordConfidence

class CharConfidence(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    percentage: builtin___float = ...
    unsure: builtin___bool = ...

    def __init__(self,
        *,
        percentage : typing___Optional[builtin___float] = None,
        unsure : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"percentage",b"percentage",u"unsure",b"unsure"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"percentage",b"percentage",u"unsure",b"unsure"]) -> None: ...
type___CharConfidence = CharConfidence
