# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foundation/proto/comparison.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foundation/proto/comparison.proto',
  package='foundation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!foundation/proto/comparison.proto\x12\nfoundation\"p\n\rComparedValue\x12\n\n\x02id\x18\x01 \x02(\t\x12\x17\n\x0ftarget_value_id\x18\x02 \x02(\t\x12\x1a\n\x12\x65xtracted_value_id\x18\x03 \x02(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x0f\n\x07message\x18\x05 \x01(\t\"A\n\x17\x43omparedValueCollection\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1a\n\x12\x63ompared_value_ids\x18\x02 \x02(\t'
)




_COMPAREDVALUE = _descriptor.Descriptor(
  name='ComparedValue',
  full_name='foundation.ComparedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ComparedValue.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_value_id', full_name='foundation.ComparedValue.target_value_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extracted_value_id', full_name='foundation.ComparedValue.extracted_value_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='foundation.ComparedValue.score', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='foundation.ComparedValue.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=161,
)


_COMPAREDVALUECOLLECTION = _descriptor.Descriptor(
  name='ComparedValueCollection',
  full_name='foundation.ComparedValueCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ComparedValueCollection.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compared_value_ids', full_name='foundation.ComparedValueCollection.compared_value_ids', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['ComparedValue'] = _COMPAREDVALUE
DESCRIPTOR.message_types_by_name['ComparedValueCollection'] = _COMPAREDVALUECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComparedValue = _reflection.GeneratedProtocolMessageType('ComparedValue', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREDVALUE,
  '__module__' : 'foundation.proto.comparison_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ComparedValue)
  })
_sym_db.RegisterMessage(ComparedValue)

ComparedValueCollection = _reflection.GeneratedProtocolMessageType('ComparedValueCollection', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREDVALUECOLLECTION,
  '__module__' : 'foundation.proto.comparison_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ComparedValueCollection)
  })
_sym_db.RegisterMessage(ComparedValueCollection)


# @@protoc_insertion_point(module_scope)
