# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extraction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='extraction.proto',
  package='foundation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65xtraction.proto\x12\nfoundation\x1a\x0c\x65ntity.proto\"\x8b\x01\n\x0e\x45xtractedValue\x12\n\n\x02id\x18\x01 \x02(\t\x12\x12\n\nfield_name\x18\x02 \x02(\t\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x18\n\x10serialized_value\x18\x04 \x01(\x0c\x12\x31\n\x0b\x65ntities_id\x18\x05 \x01(\x0b\x32\x1c.foundation.EntityCollection\"C\n\x18\x45xtractedValueCollection\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1b\n\x13\x65xtracted_value_ids\x18\x02 \x03(\t'
  ,
  dependencies=[entity__pb2.DESCRIPTOR,])




_EXTRACTEDVALUE = _descriptor.Descriptor(
  name='ExtractedValue',
  full_name='foundation.ExtractedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ExtractedValue.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='foundation.ExtractedValue.field_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='foundation.ExtractedValue.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serialized_value', full_name='foundation.ExtractedValue.serialized_value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entities_id', full_name='foundation.ExtractedValue.entities_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=186,
)


_EXTRACTEDVALUECOLLECTION = _descriptor.Descriptor(
  name='ExtractedValueCollection',
  full_name='foundation.ExtractedValueCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ExtractedValueCollection.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extracted_value_ids', full_name='foundation.ExtractedValueCollection.extracted_value_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=255,
)

_EXTRACTEDVALUE.fields_by_name['entities_id'].message_type = entity__pb2._ENTITYCOLLECTION
DESCRIPTOR.message_types_by_name['ExtractedValue'] = _EXTRACTEDVALUE
DESCRIPTOR.message_types_by_name['ExtractedValueCollection'] = _EXTRACTEDVALUECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtractedValue = _reflection.GeneratedProtocolMessageType('ExtractedValue', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDVALUE,
  '__module__' : 'extraction_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ExtractedValue)
  })
_sym_db.RegisterMessage(ExtractedValue)

ExtractedValueCollection = _reflection.GeneratedProtocolMessageType('ExtractedValueCollection', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDVALUECOLLECTION,
  '__module__' : 'extraction_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ExtractedValueCollection)
  })
_sym_db.RegisterMessage(ExtractedValueCollection)


# @@protoc_insertion_point(module_scope)
