# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foundation/proto/extraction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foundation/proto/extraction.proto',
  package='foundation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!foundation/proto/extraction.proto\x12\nfoundation\"l\n\x0e\x45xtractedValue\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfield_name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x18\n\x10serialized_value\x18\x04 \x01(\x0c\x12\x12\n\nentity_ids\x18\x05 \x03(\t\"C\n\x18\x45xtractedValueCollection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x13\x65xtracted_value_ids\x18\x02 \x03(\t'
)




_EXTRACTEDVALUE = _descriptor.Descriptor(
  name='ExtractedValue',
  full_name='foundation.ExtractedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ExtractedValue.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='foundation.ExtractedValue.field_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='foundation.ExtractedValue.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serialized_value', full_name='foundation.ExtractedValue.serialized_value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_ids', full_name='foundation.ExtractedValue.entity_ids', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=157,
)


_EXTRACTEDVALUECOLLECTION = _descriptor.Descriptor(
  name='ExtractedValueCollection',
  full_name='foundation.ExtractedValueCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.ExtractedValueCollection.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extracted_value_ids', full_name='foundation.ExtractedValueCollection.extracted_value_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['ExtractedValue'] = _EXTRACTEDVALUE
DESCRIPTOR.message_types_by_name['ExtractedValueCollection'] = _EXTRACTEDVALUECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtractedValue = _reflection.GeneratedProtocolMessageType('ExtractedValue', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDVALUE,
  '__module__' : 'foundation.proto.extraction_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ExtractedValue)
  })
_sym_db.RegisterMessage(ExtractedValue)

ExtractedValueCollection = _reflection.GeneratedProtocolMessageType('ExtractedValueCollection', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDVALUECOLLECTION,
  '__module__' : 'foundation.proto.extraction_pb2'
  # @@protoc_insertion_point(class_scope:foundation.ExtractedValueCollection)
  })
_sym_db.RegisterMessage(ExtractedValueCollection)


# @@protoc_insertion_point(module_scope)
