# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='record.proto',
  package='foundation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0crecord.proto\x12\nfoundation\"\x90\x01\n\rRecordContext\x12\n\n\x02id\x18\x01 \x02(\t\x12\x13\n\x0b\x65ntities_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63ollections_id\x18\x03 \x01(\t\x12\x10\n\x08pages_id\x18\x04 \x01(\t\x12\x17\n\x0fspatial_text_id\x18\x05 \x02(\t\x12\x1b\n\x13\x65xtracted_values_id\x18\x06 \x01(\t'
)




_RECORDCONTEXT = _descriptor.Descriptor(
  name='RecordContext',
  full_name='foundation.RecordContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.RecordContext.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entities_id', full_name='foundation.RecordContext.entities_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='collections_id', full_name='foundation.RecordContext.collections_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pages_id', full_name='foundation.RecordContext.pages_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spatial_text_id', full_name='foundation.RecordContext.spatial_text_id', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extracted_values_id', full_name='foundation.RecordContext.extracted_values_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['RecordContext'] = _RECORDCONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordContext = _reflection.GeneratedProtocolMessageType('RecordContext', (_message.Message,), {
  'DESCRIPTOR' : _RECORDCONTEXT,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:foundation.RecordContext)
  })
_sym_db.RegisterMessage(RecordContext)


# @@protoc_insertion_point(module_scope)
