# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from entity_pb2 import (
    EntityCollection as entity_pb2___EntityCollection,
)

from extraction_pb2 import (
    ExtractedValueCollection as extraction_pb2___ExtractedValueCollection,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)


class RecordContext(google___protobuf___message___Message):
    id = ... # type: typing___Text
    spatial_text_id = ... # type: typing___Text

    @property
    def entities_id(self) -> entity_pb2___EntityCollection: ...

    @property
    def collections_id(self) -> entity_pb2___EntityCollection: ...

    @property
    def pages_id(self) -> entity_pb2___EntityCollection: ...

    @property
    def extracted_values_id(self) -> extraction_pb2___ExtractedValueCollection: ...

    def __init__(self,
        id : typing___Text,
        spatial_text_id : typing___Text,
        entities_id : typing___Optional[entity_pb2___EntityCollection] = None,
        collections_id : typing___Optional[entity_pb2___EntityCollection] = None,
        pages_id : typing___Optional[entity_pb2___EntityCollection] = None,
        extracted_values_id : typing___Optional[extraction_pb2___ExtractedValueCollection] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> RecordContext: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
