# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)


class RecordContext(google___protobuf___message___Message):
    id = ... # type: typing___Text
    entities_id = ... # type: typing___Text
    collections_id = ... # type: typing___Text
    pages_id = ... # type: typing___Text
    spatial_text_id = ... # type: typing___Text
    extracted_values_id = ... # type: typing___Text

    def __init__(self,
        id : typing___Text,
        spatial_text_id : typing___Text,
        entities_id : typing___Optional[typing___Text] = None,
        collections_id : typing___Optional[typing___Text] = None,
        pages_id : typing___Optional[typing___Text] = None,
        extracted_values_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> RecordContext: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
