# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from foundation.proto.comparison_pb2 import (
    ComparedValue as foundation___proto___comparison_pb2___ComparedValue,
    ComparedValueCollection as foundation___proto___comparison_pb2___ComparedValueCollection,
)

from foundation.proto.entity_pb2 import (
    Entity as foundation___proto___entity_pb2___Entity,
    EntityCollection as foundation___proto___entity_pb2___EntityCollection,
)

from foundation.proto.extraction_pb2 import (
    ExtractedValue as foundation___proto___extraction_pb2___ExtractedValue,
    ExtractedValueCollection as foundation___proto___extraction_pb2___ExtractedValueCollection,
)

from foundation.proto.record_pb2 import (
    RecordContext as foundation___proto___record_pb2___RecordContext,
)

from foundation.proto.targets_pb2 import (
    TargetValue as foundation___proto___targets_pb2___TargetValue,
    TargetValueCollection as foundation___proto___targets_pb2___TargetValueCollection,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)


class SerializedTypeOneOf(google___protobuf___message___Message):

    @property
    def record_context(self) -> foundation___proto___record_pb2___RecordContext: ...

    @property
    def extracted_value(self) -> foundation___proto___extraction_pb2___ExtractedValue: ...

    @property
    def target_value(self) -> foundation___proto___targets_pb2___TargetValue: ...

    @property
    def compared_value(self) -> foundation___proto___comparison_pb2___ComparedValue: ...

    @property
    def entity(self) -> foundation___proto___entity_pb2___Entity: ...

    @property
    def extracted_value_collection(self) -> foundation___proto___extraction_pb2___ExtractedValueCollection: ...

    @property
    def target_value_collection(self) -> foundation___proto___targets_pb2___TargetValueCollection: ...

    @property
    def compared_value_collection(self) -> foundation___proto___comparison_pb2___ComparedValueCollection: ...

    @property
    def entity_collection(self) -> foundation___proto___entity_pb2___EntityCollection: ...

    def __init__(self,
        record_context : typing___Optional[foundation___proto___record_pb2___RecordContext] = None,
        extracted_value : typing___Optional[foundation___proto___extraction_pb2___ExtractedValue] = None,
        target_value : typing___Optional[foundation___proto___targets_pb2___TargetValue] = None,
        compared_value : typing___Optional[foundation___proto___comparison_pb2___ComparedValue] = None,
        entity : typing___Optional[foundation___proto___entity_pb2___Entity] = None,
        extracted_value_collection : typing___Optional[foundation___proto___extraction_pb2___ExtractedValueCollection] = None,
        target_value_collection : typing___Optional[foundation___proto___targets_pb2___TargetValueCollection] = None,
        compared_value_collection : typing___Optional[foundation___proto___comparison_pb2___ComparedValueCollection] = None,
        entity_collection : typing___Optional[foundation___proto___entity_pb2___EntityCollection] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SerializedTypeOneOf: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Serialized(google___protobuf___message___Message):
    class DataEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> SerializedTypeOneOf: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[SerializedTypeOneOf] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> Serialized.DataEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

    root_id = ... # type: typing___Text
    foundation_type_version = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[int]

    @property
    def data(self) -> typing___MutableMapping[typing___Text, SerializedTypeOneOf]: ...

    def __init__(self,
        root_id : typing___Text,
        data : typing___Optional[typing___Mapping[typing___Text, SerializedTypeOneOf]] = None,
        foundation_type_version : typing___Optional[typing___Iterable[int]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Serialized: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
