# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foundation/proto/targets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foundation.proto import geometry_pb2 as foundation_dot_proto_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='foundation/proto/targets.proto',
  package='foundation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x66oundation/proto/targets.proto\x12\nfoundation\x1a\x1f\x66oundation/proto/geometry.proto\"\\\n\x0bTargetValue\x12\n\n\x02id\x18\x01 \x02(\t\x12\x12\n\nfield_name\x18\x02 \x02(\t\x12\x1e\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x10.foundation.BBox\x12\r\n\x05value\x18\x04 \x02(\t\"=\n\x15TargetValueCollection\x12\n\n\x02id\x18\x01 \x02(\t\x12\x18\n\x10target_value_ids\x18\x02 \x03(\t'
  ,
  dependencies=[foundation_dot_proto_dot_geometry__pb2.DESCRIPTOR,])




_TARGETVALUE = _descriptor.Descriptor(
  name='TargetValue',
  full_name='foundation.TargetValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.TargetValue.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='foundation.TargetValue.field_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bbox', full_name='foundation.TargetValue.bbox', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='foundation.TargetValue.value', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=171,
)


_TARGETVALUECOLLECTION = _descriptor.Descriptor(
  name='TargetValueCollection',
  full_name='foundation.TargetValueCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foundation.TargetValueCollection.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_value_ids', full_name='foundation.TargetValueCollection.target_value_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=234,
)

_TARGETVALUE.fields_by_name['bbox'].message_type = foundation_dot_proto_dot_geometry__pb2._BBOX
DESCRIPTOR.message_types_by_name['TargetValue'] = _TARGETVALUE
DESCRIPTOR.message_types_by_name['TargetValueCollection'] = _TARGETVALUECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetValue = _reflection.GeneratedProtocolMessageType('TargetValue', (_message.Message,), {
  'DESCRIPTOR' : _TARGETVALUE,
  '__module__' : 'foundation.proto.targets_pb2'
  # @@protoc_insertion_point(class_scope:foundation.TargetValue)
  })
_sym_db.RegisterMessage(TargetValue)

TargetValueCollection = _reflection.GeneratedProtocolMessageType('TargetValueCollection', (_message.Message,), {
  'DESCRIPTOR' : _TARGETVALUECOLLECTION,
  '__module__' : 'foundation.proto.targets_pb2'
  # @@protoc_insertion_point(class_scope:foundation.TargetValueCollection)
  })
_sym_db.RegisterMessage(TargetValueCollection)


# @@protoc_insertion_point(module_scope)
