# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from foundation.proto.geometry_pb2 import (
    BBox as foundation___proto___geometry_pb2___BBox,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)


class TargetValue(google___protobuf___message___Message):
    id = ... # type: typing___Text
    field_name = ... # type: typing___Text
    value = ... # type: typing___Text

    @property
    def bbox(self) -> foundation___proto___geometry_pb2___BBox: ...

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        field_name : typing___Optional[typing___Text] = None,
        bbox : typing___Optional[foundation___proto___geometry_pb2___BBox] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TargetValue: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class TargetValueCollection(google___protobuf___message___Message):
    id = ... # type: typing___Text
    target_value_ids = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        target_value_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TargetValueCollection: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
